// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ee4c754d-51ac-41e5-a806-d5657faf4ed0",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_eNO2P5Sy5",
    "aws_user_pools_web_client_id": "7qft93vvafs0k88itb5bken18k",
    "aws_cloud_logic_custom": [
        {
            "name": "api",
            "endpoint": "https://3ahos1c6o3.execute-api.us-east-2.amazonaws.com/Prod",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
