// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6690e6dc-448a-4667-a901-ad018586f446",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fvQJMqOVm",
    "aws_user_pools_web_client_id": "70mbqlrkmlkcv1pspmkodstg9h",
    "aws_cloud_logic_custom": [
        {
            "name": "api",
            "endpoint": "https://w6wqe2x608.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
